language: cpp
compiler: gcc

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

install:
    # Install CMake
    - sudo apt-get install cmake

script:
    - cmake .
    - make
    - ctest -VV