language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

install:
    # Install CMake
    - sudo apt-get install cmake

script:
    - cmake .
    - make
    - ctest -VV